### ISSUE TITLE
cannot find module betfair-emulator

### ISSUE THREAD

**Issue by KieronWiltshire** [AlgoTrader/betfair#23]
Tries to find it at "opt/projects/betfair-emulator", should just be "betfair-emulator",
also underscore should be a dependency within the "betfair-emulator" package.

**Comment by AlgoTrader** [comment]
require was fixed, npm 0.6.6
underscore is NOT a depencency. lodash is

**Comment by AlgoTrader** [comment]
betfair has hard-coded obsolete version of emulator in packet.json, I fixed it

**Comment by gRoberts84** [comment]
When installing 0.6.7 via NPM, both `lib/session.js` and `src/lib/session.js` reference the `/opts/projects/betfair-emulator` package.

```
//let Emulator = require('betfair-emulator');
var Emulator = require('/opt/projects/betfair-emulator');
```

However I can see the changes within the repo?

**Comment by KieronWiltshire** [comment]
@gRoberts84 

> betfair has hard-coded obsolete version of emulator in packet.json, **I fixed it** - AlgoTrader

**Comment by gRoberts84** [comment]
FYI - The version you've just pushed to NPM no longer works.

The end user will now need to build before they can use it, where as before, it already had the built `lib` directory.

**Comment by KieronWiltshire** [comment]
My apologies.
